spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss

server:
  port: 8000

tcp-server:
  jt808:
    enable: true
    port: 7611